export const Fonts = {
  bold: 'Poppins-Bold',
  medium: 'Poppins-Medium',
  regular: 'Poppins-Regular',
  semibold: 'Poppins-SemiBold',
  roboto: {
    medium: 'Roboto-Medium',
    regular: 'Roboto-Regular',
  },
  nunito: {
    light: 'Nunito-Light',
    medium: 'Nunito-Medium',
    regular: 'Nunito-Regular',
    semibold: 'Nunito-SemiBold',
  },
};

export const Colors = {
  primary: '#ffd700',
  primaryLight: '#efd4d7',
  whiteColor: '#ffffff',
  blackColor: '#0d0d0d',
  lightGrey: '#f2f2f3',
  colorGrey: '#616161',
  orangeColor: '#ffd90d',
  colorOrange: '#ff7000',
  colorGold: '#FFCE00',
  greenColor: '#43a047',
  lightRedColor: '#F16767', //"#e57373",
};

export const Sizes = {
  base: 8,
  small: 12,
  xmedium: 16,
  medium: 17,
  large: 24,
  extraLarge: 32,
};

export const Images = {
  back: require('./images/left-arrow.png'),
  login_image: require('./images/login.jpg'),
  login_image2: require('./images/login_image.jpg'),
  app_icon: require('./images/app_icon.png'),
  splash_image: require('./images/splash.png'),
  confidential: require('./images/confidential.png'),
  verifiedAccount: require('./images/verified-account.png'),
  payment: require('./images/payment.png'),
  wallet: require('./images/wallet.png'),
  customerService: require('./images/customer-service.png'),
  blog: require('./images/error.png'),
  user: require('./images/user.png'),
  shopBag: require('./images/shopping_bag.png'),
  userProfile: require('./images/user-profile.png'),
  closeRound: require('./images/close.png'),
  yearlyImage: require('./images/horoscope2022.png'),
  palmistry: require('./images/palmistry.jpg'),
  whatsapp: require('./images/whatsapp.png'),
  sky: require('./images/sky.jpg'),
  male: require('./images/maleGender.png'),
  female: require('./images/femaleGender.png'),
  otherGender: require('./images/otherGender.png'),
  southAstroChart: require('./images/south-astro-chart.jpg'),
  deafultUser: require('./images/no_customer_image.png'),
  youtube: require('./images/youtube.png'),
  noData: require('./images/nodata.png'),
  noDataFound: require('./images/noDataFound.png'),
  right: require('./images/right.png'),
  translation: require('./images/translation.png'),
  astrologerImage: require('./images/astrologerImage.png'),
  vedicAstro: require('./images/vedicAstro.jpg'),
  logo: require('./images/logo.png'),
  verifyAstro: require('./images/tick-mark.png'),
  gmail: require('./images/gmail.png'),
  emptyMessageScreen: require('./images/no-message.jpeg'),
  banner1: require('./banner/banner_1.jpg'),
  banner2: require('./banner/banner_2.jpg'),
  chatScreenBannerImg: require('./banner/banner_img.png'),
  headerImage: require('./images/header.png'),
  ratingChart: require('./images/rating-chart.png'),
  readingIcon: require('./icons/reading.png'),
  languageIcon: require('./icons/language.png'),
  expIcon: require('./icons/exp.png'),
  namaste: require('./icons/namaste.png'),
  priceIcon: require('./icons/price.png'),
  NoData: require('./images/db-empty.jpg'),
  history: require('./icons/history.png'),
  Notification: require('./icons/notification.png'),
  setting: require('./icons/settings.png'),
  userLineIcon: require('./icons/user.png'),
  home: require('./icons/home.png'),
  imagePlaceholder: require('./images/avatar_placeholder.png'),
  splashLogo: require('./images/splash_logo.png'),
  splashBackground: require('./images/splash_bg.png'),
  FreeSessionOffer: require('./images/free_chat_offer.jpg'),
  AppLogo: require('./images/play_store_512.png'),
  AppLogo3D: require('./images/app_logo_3d.png'),
  Dollar: require('./images/dollar.png'),
  Flirt: require('./images/flirt.png'),
  OnlinePay: require('./images/online-payment.png'),
  RightIcon: require('./icons/right.png'),
  Funding: require('./images/funding.png'),
  Success: require('./icons/check.png'),
  ErrorIcon: require('./icons/mark.png'),
  Warning: require('./icons/warning.png'),
  Book: require('./icons/manual-book.png'),
  Coin: require('./images/coin.png'),
};

export const homeCategory = [
  { id: 1, name: 'Married Life', image: require('../assets/icons/married_life.png') },
  { id: 2, name: 'Money & Finance', image: require('../assets/icons/money_finance.png') },
  { id: 3, name: 'Love & Releationship', image: require('../assets/icons/love_relation.png') },
  { id: 4, name: 'Kids', image: require('../assets/icons/kids.png') },
  { id: 5, name: 'Carrer & Jobs', image: require('../assets/icons/carrer_job.png') },
  { id: 6, name: 'Education', image: require('../assets/icons/education.png') },
];
